### ISSUE TITLE
More recent R40 user manual available? More recent 3.10 sources

### ISSUE THREAD

**Issue by ThomasKaiser** [tinalinux/linux-3.10#1]
Hi,

now that you officially released a Tinalinux code drop for R40 what about updating documentation? Is there a new R40 User manual available in the meantime? If so can you please put it online?

Then why is your kernel still at 3.10.65? Please have a look into @dan-and repos -- he patched the 3.10 kernel up to [3.10.104](https://github.com/dan-and/BPI-M2U-bsp) (based on another BSP code drop from some months ago)

**Comment by Icenowy** [comment]
Yes, updateing kernel is a seriously required thing for IoT devices.

3.10.65 is a kernel very easy to attack.

for example, the famous dirtycow bug can be easily used on 3.10.65.

对于 IoT 而言，升级内核非常重要。

3.10.65 非常容易攻击。

比如前几天的“脏牛”（dirtycow） bug 在 3.10.65 上可以直接利用

**Comment by tracewong** [comment]
@Icenowy ths for your report, i will fixed dirtycow bug.
@ThomasKaiser kernel upgrade is a big things for us. so we cover secure patches from kernel mainline.

@Icenowy 感谢你的报告，我会马上修复dirtycow的bug。
@ThomasKaiser 内核升级对我们来说意味着很长的测试周期，所以我们发布的版本上主要关注主线内核上已经修复的安全问题的补丁。

**Comment by tracewong** [comment]
@Icenowy dirtycow bug had fixed before "r40 tina linux v1.0 release". ths

**Comment by ThomasKaiser** [comment]
@tracewong What about new version of R40 user manual?

BTW: Are you aware that linux-sunxi community runs mainline kernel already on your SoCs (even R40)? And that it would be really helpful if you could contribute to these efforts?

**Comment by tracewong** [comment]
@ThomasKaiser I have push our team to release R40 user manual and datasheet, those documents will release at https://github.com/allwinner-zh/documents.

I know linux-sunxi community, I hope linux-kernel mainline could supprot sunxi socs at last. I will do this try my best.

**Comment by ThomasKaiser** [comment]
@tracewong 

>  I have push our team to release R40 user manual and datasheet, those documents will release at https://github.com/allwinner-zh/documents.

Any news on this? :)

**Comment by tracewong** [comment]
@ThomasKaiser  R40 user manual and datasheet release at github.com/tinalinux/docs repo, r40-v1.y branch.

**Comment by ThomasKaiser** [comment]
@tracewong Thank you!
